/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'virusEPS'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct _RTL_USER_PROCESS_PARAMETERS;

/* 171 */
struct _LIST_ENTRY
{
  _LIST_ENTRY *Flink;
  _LIST_ENTRY *Blink;
};

/* 172 */
struct _PEB_LDR_DATA
{
  char Reserved1[8];
  void *Reserved2[3];
  _LIST_ENTRY InMemoryOrderModuleList;
};

/* 178 */
struct _PEB
{
  char Reserved1[2];
  char BeingDebugged;
  char Reserved2[1];
  void *Reserved3[2];
  _PEB_LDR_DATA *Ldr;
  _RTL_USER_PROCESS_PARAMETERS *ProcessParameters;
  void *Reserved4[3];
  void *AtlThunkSListPtr;
  void *Reserved5;
  unsigned int Reserved6;
  void *Reserved7;
  unsigned int Reserved8;
  unsigned int AtlThunkSListPtr32;
  void *Reserved9[45];
  char Reserved10[96];
  void (__stdcall *PostProcessInitRoutine)();
  char Reserved11[128];
  void *Reserved12[1];
  unsigned int SessionId;
};

/* 117 */
typedef unsigned __int16 wchar_t;

/* 156 */
struct _UNICODE_STRING
{
  unsigned __int16 Length;
  unsigned __int16 MaximumLength;
  wchar_t *Buffer;
};

/* 170 */
struct _RTL_USER_PROCESS_PARAMETERS
{
  char Reserved1[16];
  void *Reserved2[10];
  _UNICODE_STRING ImagePathName;
  _UNICODE_STRING CommandLine;
};

